

CREATE TABLE lists (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
name TEXT DEFAULT NULL,
created_at TEXT DEFAULT NULL,
updated_at TEXT DEFAULT NULL
);

CREATE TABLE tasks (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
description TEXT DEFAULT NULL,
complete INTEGER DEFAULT NULL,
list_id NUMERIC DEFAULT NULL REFERENCES lists (id),
created_at TEXT DEFAULT NULL,
updated_at TEXT DEFAULT NULL
);


